### ISSUE TITLE
Changing the data set

### ISSUE THREAD

**Issue by ruben1dlg** [UBC-MDS/olympic_medal_htest#10]
According to the discussion we've had on slack, we are changing the data set that we will be using and our statistical question.
We will use the Olympics data set to answer the question: Is the proportion of athletes under 30 that have won a medal greater than the proportion of athletes 30 and older that have won a medal. Does everyone agree with this change?

**Comment by ming0701** [comment]
Agree as discussed.

**Comment by stevenleung2018** [comment]
Sounds good.
