### ISSUE TITLE
Performance limit of altair

### ISSUE THREAD

**Issue by stevenleung2018** [UBC-MDS/olympic_medal_htest#12]
Please note that I found that Altair started to choke when I tried to do more than about 3 repeated/faceted plots with 270k+ rows in the data frame.  After I removed all rows without medals, the limit on repeated/faceted plots seem to go away.  We just need to be more careful when we try to plot anything with that many rows.  

The workaround is to break them up into single plots.

**Comment by ruben1dlg** [comment]
Perfect Steven! Thank you so much for the info 👍🏻

**Comment by stevenleung2018** [comment]
No further issue has been found with altair.
