### ISSUE TITLE
Dependencies of scripts 04_htest.R and 04_htest.Rmd

### ISSUE THREAD

**Issue by ming0701** [UBC-MDS/olympic_medal_htest#18]
@squisty Below are the dependencies for your part.

Script 04_htest.R & 04_htest.Rmd
library(tidyverse)
library(broom)
library(infer)
library(docopt)
library(knitr)
library(kableExtra)

My computer:
macOS Big Sur version 11.5.2

R version: 4.1.0

R packages:
tidyverse :1.3.1
broom : 0.7.9
infer: 1.0.0
docopt: 0.7.1
knitr :1.33
kableExtra: 1.3.4

**Comment by stevenleung2018** [comment]
Looks ok to me.  No special comment.

**Comment by ruben1dlg** [comment]
Perfect! I'll also cite knitr and kableExtra!

**Comment by squisty** [comment]
Fantastic, I've got all those down in the dependencies
