### ISSUE TITLE
Location of Htest Rmd file

### ISSUE THREAD

**Issue by ruben1dlg** [UBC-MDS/olympic_medal_htest#20]
@ming0701 could you help me moving the Htest Rmd file to the results folder? The rest of the Rmd files are in that folder 😅

**Comment by ruben1dlg** [comment]
Also I just found out that the labels for the code chunks cannot be repeated among the documents that we are using. Could you rename your 'setup' and 'summary' code chunks to something like 'setuphtest', 'summaryhtest' ? Thanks!

**Comment by ming0701** [comment]
Done
