### ISSUE TITLE
Script Usage command lines

### ISSUE THREAD

**Issue by ruben1dlg** [UBC-MDS/olympic_medal_htest#23]
Hello guys! I am opening this issue to have record of the commands we need to run to follow our scripts. @squisty this will be helpful for the 'Usage' part of the readme file:

Reads the raw data:
python src/01_download_data.py --url="https://github.com/rfordatascience/tidytuesday/raw/master/data/2021/2021-07-27/olympics.csv" --saving_path="data/raw/olympics.csv"

Cleans the data:
python src/02_cleaning.py --reading_path="data/raw/olympics.csv" --saving_path="data/olympics_cleaned.csv"

Creates EDA figures and tables:
python src/03_EDA_olympics.py --reading_path="data/olympics_cleaned.csv" --saving_path="results"

Generates html for the complete EDA document:
Rscript -e "rmarkdown::render('results/03_EDA.Rmd')"

Generates Hypothesis test figures and tables:
Rscript src/04_htest.R --data="data/olympics_cleaned.csv" --saving_path="results"

Generates an html and md file of the final report:
Rscript -e "rmarkdown::render('results/05_final_report.Rmd', 'all', output_dir='doc')"

**Comment by squisty** [comment]
Fantastic, this helps me out quite a bit. Thanks!
