### ISSUE TITLE
The analytics question

### ISSUE THREAD

**Issue by stevenleung2018** [UBC-MDS/olympic_medal_htest#3]
@ming0701 reminded me in slack regarding that due to the level of our knowledge and also the time constraints of this course project, we might need to readjust the analytics question we might want to ask in this project.

I agree.  Based on our phone conversation, even if we are working on a prediction model, we are really TRYING to see whether we can really predict the Worldwide Gross Income (a.k.a. Worldwide Box Office) with the data set of the movies.  We may attempt to train a regression model and see but we may not attempt to optimize the hyper parameters sufficiently to have a very robust solution.

**Comment by squisty** [comment]
I think thats the most realistic outcome of what we can do here, based off of what we know how to do and what we can actually do with a data set this large.

**Comment by ruben1dlg** [comment]
Yes! I totally agree. I think that is a more 'down to earth' approach to what we would be able to accomplish with the model.

**Comment by ming0701** [comment]
Good to have a consensus on this. I think the main focus of this project is more on the workflow and collaboration, meanwhile we just need to be comfortable with our prediction instead of setting high standard on the prediction accuracy.

**Comment by ruben1dlg** [comment]
Just an update for this issue: We encountered some problems regarding the source of the data set that we were using, and changed it for the Olympics data set. Also, our question changed from a predictive question to an inferential question, and we are going to use a hypothesis test now instead of a machine learning model.
