### ISSUE TITLE
Makefile - file report

### ISSUE THREAD

**Issue by ming0701** [UBC-MDS/olympic_medal_htest#34]
In our makefile, the final report will be rendered as .Rmd file, shall we also render the .md (can be rendered on github) and .html file?

**Comment by stevenleung2018** [comment]
Just to be clear, the `.Rmd` files are not rendered.  They are written by us.  The `.md` and HTML files are rendered.  To answer Brandon's question, I think we should save a static copy of the final report in HTML format for sure.  I'm open to saving the `.md` file there as well, but if we do that, we will also need to save the figures (PNG files) too.

**Comment by ming0701** [comment]
I'm fine with .Rmd and .HTML file, we can skip .md
