### ISSUE TITLE
can't see figures in final report.md

### ISSUE THREAD

**Issue by ming0701** [UBC-MDS/olympic_medal_htest#37]
https://github.com/UBC-MDS/olympic_medal_htest/blob/main/doc/05_final_report.md
Do we need to upload those png files to repo so that the figures can be shown in the final report.md?

**Comment by ming0701** [comment]
I just tested in my own repo, it will only work if I push the png files to doc folder, but likely we should push those png files under results folder?
https://github.com/ming0701/box_office_predictions/blob/main/doc/05_final_report.md

**Comment by stevenleung2018** [comment]
How about just move the final report to the `results` folder and ask the readers to look there?  Then the `.md` should work and the change will be minimal.

**Comment by stevenleung2018** [comment]
Actually there is another solution - We do not have to commit the `.md` file to the repo to avoid the confusion that the report is rendered on GitHub without the diagrams.

FYI, Tiffany did NOT include the `.md` file in the `doc` folder.  (https://github.com/ttimbers/breast_cancer_predictor/tree/master/doc)  (She did provided the HTML file and also `.Rmd` and `.bib` files.)

I also remember seeing Florencia wrote something like that the final report can be in HTML or PDF.  But I can't find the link to the slack/GitHub message regarding this.

**Comment by stevenleung2018** [comment]
Should we close this one?  I suggest that we should just remove the `.md` file and only keep the HTML file of the final report in the repo.

**Comment by stevenleung2018** [comment]
`.md` file for final report has been removed.
