### ISSUE TITLE
Four feedback to TA's review and peer reviews:

### ISSUE THREAD

**Issue by stevenleung2018** [UBC-MDS/olympic_medal_htest#38]
As said, for each point, please state (a) which point you are addressing and how you are addressing and (b) a link to the commit with the change for instructors to check.  For your reference, requirements of Milestone4:
https://pages.github.ubc.ca/mds-2021-22/DSCI_522_dsci-workflows_students/materials/assignments/milestone4.html
TA's review:
https://github.com/UBC-MDS/olympic_medal_htest/issues/28#issue-1067799769
Peer reviews:
https://github.com/UBC-MDS/data-analysis-review-2021/issues/26
Thanks.

**Comment by ming0701** [comment]
**#1** 
Feedback:
https://github.com/UBC-MDS/olympic_medal_htest/issues/28#issue-1067799769
point 2: the licence should be copyrighted to your names not MDS (it is your work)
Links to commit:
https://github.com/UBC-MDS/olympic_medal_htest/commit/b5ae25f682e8013cc0a6230c8ef9d58ef4c1d127

**#2**
Feedback:
https://github.com/UBC-MDS/olympic_medal_htest/issues/28#issue-1067799769
point 3: 
Question could be restated for clarity, something like: Is age associated with success at the Olympics?
Is the idea to compare age categories given all other features being equal? Why was 25 chosen as the cutoff?
What kind of visualization do you plan to make?
Links to commit:
https://github.com/UBC-MDS/olympic_medal_htest/commit/97c878cc308dcf406b744999d54c6f6092671b81

**Comment by stevenleung2018** [comment]
FYI, the comment for the "Four responses" (https://github.com/UBC-MDS/data-analysis-review-2021/issues/26#issuecomment-988663071) is almost done.  Now pending on the PR to be completed so that I can put the commit link there.

**Comment by stevenleung2018** [comment]
I'm closing this issue because the 4 responses have been done.  Here is the link.

Since we may work on Milestone2 feedback, if time permits I may choose any feedback which is more noteworthy than those 4 we already have.  Or we just append to the list.  If you think there is any change noteworthy to be added to the list (by Friday night), please add a comment to the issue Milestone2 feedback.

Thanks for all the work.

**Comment by ming0701** [comment]
#3
Feedback:
https://github.com/UBC-MDS/olympic_medal_htest/issues/42
point 4:
I'm confused by the result: if the true diff is -0.025 then it's absolute value is much greater than your significance threshold and it's far outside the null distribution. This seems like the opposite conclusion to the one you make...
Links to commit:
https://github.com/UBC-MDS/olympic_medal_htest/commit/9f2cb27f8528dd2298550ff301a72141b9a6b5a5

**Comment by stevenleung2018** [comment]
Thanks.  FYI, added to the list as Response #5.
https://github.com/UBC-MDS/data-analysis-review-2021/issues/26#issuecomment-988663071
