### ISSUE TITLE
Reviews from users / critics vs Gross Income

### ISSUE THREAD

**Issue by ruben1dlg** [UBC-MDS/olympic_medal_htest#5]
Hi team! I have one question, we have the following in our EDA file: "Reviews from users seem to correlate more prominently with worldwide gross income compared to reviews from critics." I would think it is the other way around isn't it? 
![image](https://user-images.githubusercontent.com/90015620/142678365-b5e86c94-13e4-41b0-bfe8-db69d19a311a.png)

**Comment by ming0701** [comment]
Hi Ruben,  seems like the income depends on the number of reviews no matter this is good or bad.  Higher no. of reviews -> more people watching -> higher income
